update from std@0.110.0 to std@0.177.0
Because std@0.110.0 used Deno.version which is not supported in
deploy-deploy.

This fixes the error:
TypeError: Cannot read properties of undefined (reading 'deno')
    at https://deno.land/std@0.110.0/node/process.ts:73:108